repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet format ./Syntax-Sorcerers/muthana/muthana.sln --verify-no-changes
        language: system
        files: "\\.cs$"
        pass_filenames: false
        always_run: true

      - id: roslyn-analyzers
        name: Roslyn Analyzer Build Check
        entry: dotnet build ./Syntax-Sorcerers/muthana/muthana.sln --no-restore --warnaserror
        language: system
        files: "\\.cs$"
        pass_filenames: false
        always_run: true
